version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DATABASE_HOST: 'db'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build: .
    command: celery -A employee_management worker -l info
    env_file:
      - .env
    environment:
      DATABASE_HOST: 'db'
    depends_on:
      - redis
      - db
    networks:
      - app_network
    user: "1000:1000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge