# Generated by Django 4.0.10 on 2024-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_position_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary'),
        ),
    ]
